"""add table user

Revision ID: 81571a469698
Revises: d8579c66a347
Create Date: 2024-10-23 15:37:03.732315

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "81571a469698"
down_revision: Union[str, None] = "d8579c66a347"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("tg_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("tg_id"),
    )
    op.add_column(
        "user_vpn", sa.Column("tg_user_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(None, "user_vpn", "users", ["tg_user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_vpn", type_="foreignkey")
    op.drop_column("user_vpn", "tg_user_id")
    op.drop_table("users")
    # ### end Alembic commands ###
