"""add status enum field in user_vpn

Revision ID: cd6ac360e04d
Revises: 9a79219d8c0b
Create Date: 2024-10-27 18:33:31.778017

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

status_user_vpn = postgresql.ENUM("active", "inactive", "pause", name="status_user_vpn")

# revision identifiers, used by Alembic.
revision: str = "cd6ac360e04d"
down_revision: Union[str, None] = "9a79219d8c0b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    status_user_vpn.create(op.get_bind(), checkfirst=False)
    op.add_column(
        "user_vpn",
        sa.Column(
            "status",
            status_user_vpn,
            nullable=False,
            comment="Состояние купленного впн",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    status_user_vpn.drop(op.get_bind(), checkfirst=False)
    op.drop_column("user_vpn", "status")
    # ### end Alembic commands ###
