"""del tg_user_id in userv_vpn table

Revision ID: 082f15ffc53b
Revises: 67d498d8d279
Create Date: 2024-10-23 15:35:22.023283

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "082f15ffc53b"
down_revision: Union[str, None] = "67d498d8d279"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "user_vpn_tg_user_id_fkey", "user_vpn", type_="foreignkey"
    )
    op.drop_column("user_vpn", "tg_user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_vpn",
        sa.Column(
            "tg_user_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.create_foreign_key(
        "user_vpn_tg_user_id_fkey", "user_vpn", "users", ["tg_user_id"], ["id"]
    )
    # ### end Alembic commands ###
