"""create payments and orders table

Revision ID: 40dbc7ed1ae7
Revises: 60be93d219d6
Create Date: 2024-11-06 17:38:42.721252

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


payment_currency = postgresql.ENUM("dollars", "euro", "ruble", name="payment_currency")
payment_status = postgresql.ENUM("dollars", "euro", "ruble", name="payment_status")

# revision identifiers, used by Alembic.
revision: str = "40dbc7ed1ae7"
down_revision: Union[str, None] = "60be93d219d6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orders",
        sa.Column("price_id", sa.Integer(), nullable=False),
        sa.Column("tg_user_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.Boolean(), nullable=False, comment="Статус заказа"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["price_id"],
            ["prices.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tg_user_id"],
            ["tg_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "payments",
        sa.Column(
            "currency",
            payment_currency,
            nullable=False,
            comment="Валюта",
        ),
        sa.Column(
            "status",
            payment_status,
            nullable=False,
            comment="Статус платежа",
        ),
        sa.Column("amount", sa.Integer(), nullable=False, comment="Сумма"),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("payments")
    op.drop_table("orders")
    payment_currency.drop(op.get_bind(), checkfirst=False)
    payment_status.drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
