"""add tg_user_id in user_vpn table

Revision ID: 67d498d8d279
Revises: e2e2b1b01725
Create Date: 2024-10-23 15:25:12.341996

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "67d498d8d279"
down_revision: Union[str, None] = "e2e2b1b01725"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_vpn", sa.Column("tg_user_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(None, "user_vpn", "users", ["tg_user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_vpn", type_="foreignkey")
    op.drop_column("user_vpn", "tg_user_id")
    # ### end Alembic commands ###
