"""create price vpn  tables

Revision ID: c4d78448b4e6
Revises: 229715facc1c
Create Date: 2024-10-26 16:33:02.606489

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

price_term = postgresql.ENUM("day", "month", "year", name="price_term")

# revision identifiers, used by Alembic.
revision: str = "c4d78448b4e6"
down_revision: Union[str, None] = "229715facc1c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vpn",
        sa.Column("country_view_text", sa.String(length=255), nullable=False),
        sa.Column("key_country", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "price",
        sa.Column("price_view_text", sa.String(length=255), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column(
            "term",
            price_term,
            nullable=False,
            comment="Вид времени",
        ),
        sa.Column(
            "key_price",
            sa.String(length=255),
            nullable=True,
            comment="Ключ для цены",
        ),
        sa.Column("vpn_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["vpn_id"],
            ["vpn.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key_price"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TYPE price_term CASCADE")
    op.drop_table("price")
    op.drop_table("vpn")
    # ### end Alembic commands ###
