"""set vpn_key unique=True in user_vpn_s

Revision ID: 35e22b54a56e
Revises: 40dbc7ed1ae7
Create Date: 2024-11-07 14:55:59.282193

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "35e22b54a56e"
down_revision: Union[str, None] = "40dbc7ed1ae7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_vpn_s", sa.Column("vpn", sa.String(length=255), nullable=False))
    op.create_unique_constraint("unique_user_vpn_s", "user_vpn_s", ["vpn_key"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_vpn_s", "vpn")
    op.drop_constraint("unique_user_vpn_s", "user_vpn_s", type_="unique")
    # ### end Alembic commands ###
