"""set unique=True key_country in vpn, and add fk user_vpn to price

Revision ID: 75a8132eed2e
Revises: c4d78448b4e6
Create Date: 2024-10-27 15:55:02.698114

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "75a8132eed2e"
down_revision: Union[str, None] = "c4d78448b4e6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_vpn", sa.Column("view", sa.String(length=255), nullable=False))
    op.add_column("user_vpn", sa.Column("price_id", sa.Integer(), nullable=False))
    op.create_foreign_key("price_user_vpn", "user_vpn", "price", ["price_id"], ["id"])
    op.drop_column("user_vpn", "country")
    op.drop_column("user_vpn", "key_price")
    op.drop_column("user_vpn", "key_country")
    op.drop_column("user_vpn", "price")
    op.create_unique_constraint("vpn_key_country", "vpn", ["key_country"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("vpn_key_country", "vpn", type_="unique")
    op.add_column(
        "user_vpn",
        sa.Column(
            "price",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "user_vpn",
        sa.Column(
            "key_country",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "user_vpn",
        sa.Column(
            "key_price",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "user_vpn",
        sa.Column(
            "country",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint("price_user_vpn", "user_vpn", type_="foreignkey")
    op.drop_column("user_vpn", "price_id")
    op.drop_column("user_vpn", "view")
    # ### end Alembic commands ###
