"""fix type str > int in price_id field in user_vpn

Revision ID: 9a79219d8c0b
Revises: 75a8132eed2e
Create Date: 2024-10-27 16:33:22.492136

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9a79219d8c0b"
down_revision: Union[str, None] = "75a8132eed2e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
