"""set nullable True key_price field in price

Revision ID: acbf70904c9d
Revises: 9c7063ccb0ed
Create Date: 2024-10-26 15:41:13.116143

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "acbf70904c9d"
down_revision: Union[str, None] = "9c7063ccb0ed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "price",
        "key_price",
        existing_type=sa.VARCHAR(length=255),
        nullable=True,
        existing_comment="Ключ для цены",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "price",
        "key_price",
        existing_type=sa.VARCHAR(length=255),
        nullable=False,
        existing_comment="Ключ для цены",
    )
    # ### end Alembic commands ###
